# Generated by Django 3.2.5 on 2021-08-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_remove_book_favorite'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, related_name='favorite', to='library.book'),
        ),
    ]
